apiVersion: v1
kind: Service
metadata:
  name: agsr-test-task-service
  namespace: agsr-test-task-namespace
  labels:
    app: agsr-test-task
spec:
  selector:
    app: agsr-test-task
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001
