apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.name" . }}
  namespace: {{ include "chart.name" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  message: "AGSR test task"
