apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.name" . }}
  namespace: {{ include "chart.name" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "chart.selectorLabels" . | nindent 6 }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
